### ISSUE TITLE
Background on QR image

### ISSUE THREAD

**Issue by jimus888** [TeraTech/MMM-WiFiPassword#8]
Hi,

Is there an issue with the QR code background? I have a white box around my QR as shown in the picture here.

I have tried removing and reinstalling the module and moving the position to different areas of the screen

![wifi qr code1](https://user-images.githubusercontent.com/75463370/101338449-182f3780-38d1-11eb-8f14-46a073609546.jpg)

**Comment by TeraTech** [comment]
See https://github.com/TeraTech/MMM-WiFiPassword/issues/5

**Comment by jimus888** [comment]
Hi,

Thanks, got it to work with inverting the colours.

**Comment by Antgr36** [comment]
Hello. I know that the topic is too old but since I cannot find an answer anywhere else I thought give it a try here. I have the same problem. When I scan the qr code I can see my ssid and password in the scan app (so the module is working) but if I press "connect to network" nothing happens. I already tried changing colors as well as add paddings but same result. Also changing module's position and size didn't work either. I have tried 3 different scan apps but same result. Does anyone facing the same problem? Thank you in advance.

**Comment by TeraTech** [comment]
It's possible that your device is not configured to parse and execute the WIFI command from the QrCode.  See lines 35-41 of MMM-WiFiPassword.js to see the how the string is built.  The QR code is just that string codified.   If your device is reading the code but not reacting to it, then the module is working.  I hope that helps!
